### ISSUE TITLE
Disconnect upon race completion

### ISSUE THREAD

**Issue by Butteryknife** [TrollskogenMC/racing#66]
**Racing version**
3.0.0

**Server software including version**
Paper 1.16.1#135(https://papermc.io/api/v1/paper/1.16.1/135/download)

**ProtocolLib version**
v4.6.0-SNAPSHOT
Also tested on v4.5.1

**Describe the bug**
All players participating in a race will be disconnected from the server once everyone has finished. Players are sent back to hub server.

**To Reproduce**
1. Start race
2. Once you pass the final checkpoint you are disconnected from the server and brought to hub server.

Server log of event:

![t8K7tBJ](https://user-images.githubusercontent.com/69657068/90206736-70867a80-ddb2-11ea-89c5-febe10c6da52.png)

Message recieved when transferred back to hub server:

![XbsIOch](https://user-images.githubusercontent.com/69657068/90206800-914ed000-ddb2-11ea-9d81-cdee58f99d37.png)

*Note: The server does not go down/crash when a race is completed & leaderboards are updated correctly

**Expected behavior**
Expected to be brought back to location prior to joining race

**Is the bug caused by another plugin?**
Unsure. I have a feeling it is something on our end causing this but I am not sure what it could be.

**Video**
Video of race start & disconnect (https://streamable.com/itjn7u)

**Comment by hornta** [comment]
Can you post the contents of config.yml either in pastebin or formatted like this:
```
abc: 123
```

**Comment by Butteryknife** [comment]
I've tested teleport_after_race set to false as well, same result.
```
version: 5
language: english
locale: en
songs_directory: songs
storage:
  current: FILE
  file:
    directory: races
prepare_time: 30
race_announce_intervals:
- 15
- 5
countdown: 5
respawn:
  player:
    death: FROM_LAST_CHECKPOINT
    interact: NONE
  elytra:
    death: FROM_START
    interact: FROM_START
  pig:
    death: FROM_LAST_CHECKPOINT
    interact: NONE
  horse:
    death: FROM_LAST_CHECKPOINT
    interact: NONE
  boat:
    death: FROM_LAST_CHECKPOINT
    interact: NONE
  minecart:
    death: FROM_LAST_CHECKPOINT
    interact: FROM_LAST_CHECKPOINT
  strider:
    death: FROM_LAST_CHECKPOINT
    interact: NONE
discord:
  enabled: false
  bot_token: ''
  announce_channel: ''
adventure_mode_on_start: true
elytra_respawn_on_ground: true
blocked_commands:
- spawn
- wild
- wilderness
- rtp
- tpa
- tpo
- tp
- tpahere
- tpaccept
- tpdeny
- tpyes
- tpno
- tppos
- warp
- home
- rc spawn
- racing spawn
prevent_join_from_game_mode: []
start_on_join:
  sign: false
  command: false
teleport_after_race:
  enabled: true
  when: EVERYONE_FINISHES
verbose: false
checkpoint_particles_during_race: true
scoreboard:
  enabled: true
  display_milliseconds: false
  display_world_record: true
  display_world_record_holder: true
  display_world_record_fastest_lap: false
  display_world_record_fastest_lap_holder: false
  display_personal_record: true
  display_record_fastest_lap: false
  display_time: true
  display_lap_time: false
  display_fastest_lap: false
  ticks_per_update: 1
allow_chorus_fruit_tp: false
allow_ender_pearl_tp: false
allow_food_level_change: false
hd_top_list:
  directory: hologram_toplists
  show_header: true
  show_footer: false
broadcast_stop_message: true
broadcast_player_join_message: true
broadcast_cancel_message: true
broadcast_result_message: true
broadcast_start_race_message: true
prevent_join_from_world:
- bowwarfare
- spleef
- lobby
```
